version: '3.4'

services:
  benchmarks-csharp:
    image: benchmarks-csharp
    build:
      context: .
      dockerfile: Benchmarks.CSharp/Dockerfile

  benchmarks-fsharp:
    image: benchmarks-fsharp
    build:
      context: .
      dockerfile: Benchmarks.FSharp/Dockerfile
