//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeetCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeetCode.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark not found &apos;{0}&apos;.
        /// </summary>
        internal static string BenchmarkSettings_Error_BenchmarkNotFound {
            get {
                return ResourceManager.GetString("BenchmarkSettings_Error_BenchmarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --csharp and --fsharp options are mutually exclusive.
        /// </summary>
        internal static string BenchmarkSettings_Error_MutuallyExclusive {
            get {
                return ResourceManager.GetString("BenchmarkSettings_Error_MutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.
        /// </summary>
        internal static string Command_App {
            get {
                return ResourceManager.GetString("Command_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run interactive console application.
        /// </summary>
        internal static string Command_App_Description {
            get {
                return ResourceManager.GetString("Command_App_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to benchmark.
        /// </summary>
        internal static string Command_Benchmark {
            get {
                return ResourceManager.GetString("Command_Benchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run benchmarks against leetcode problems.
        /// </summary>
        internal static string Command_Benchmark_Description {
            get {
                return ResourceManager.GetString("Command_Benchmark_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string Command_Info {
            get {
                return ResourceManager.GetString("Command_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show information about a problem.
        /// </summary>
        internal static string Command_Info_Description {
            get {
                return ResourceManager.GetString("Command_Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string Command_List {
            get {
                return ResourceManager.GetString("Command_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List information about problems.
        /// </summary>
        internal static string Command_List_Description {
            get {
                return ResourceManager.GetString("Command_List_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflow.
        /// </summary>
        internal static string Command_Workflow {
            get {
                return ResourceManager.GetString("Command_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run benchmarks for a GitHub workflow.
        /// </summary>
        internal static string Command_Workflow_Description {
            get {
                return ResourceManager.GetString("Command_Workflow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     __                __   ______            __
        ///   / /   ___   ___   / /_ / ____/____   ____/ /___
        ///  / /   / _ \ / _ \ / __// /    / __ \ / __  // _ \
        /// / /___/  __//  __// /_ / /___ / /_/ // /_/ //  __/
        /// /_____/\___/ \___/ \__/ \____/ \____/ \__,_/ \___/.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
