name: Build and Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # TODO: Change back to net7.0 once dotnet format issue is resolved
  DOTNET_FRAMEWORK: net6.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          # TODO: Add net7.0 back once dotnet format issue is resolved
          dotnet-version: |
            6.0.x

      - name: Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: Run dotnet format
        id: format
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Run dotnet test
        id: test
        run: dotnet test --configuration Release

  benchmark:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          # TODO: Add net7.0 back once dotnet format issue is resolved
          dotnet-version: |
            6.0.x

      - name: List problems
        id: list-problems
        run: |
          dotnet run \
            --project ./LeetCode.ConsoleApp/LeetCode.ConsoleApp.csproj \
            list

      - name: Run benchmarks
        id: run-benchmarks
        run: |
          dotnet run \
            --project ./LeetCode.ConsoleApp/LeetCode.ConsoleApp.csproj \
            --framework $DOTNET_FRAMEWORK \
            --configuration Release \
            workflow

      - name: Store benchmark results
        id: store-benchmarks
        if: ${{ github.event_name == 'push' }}
        uses: benchmark-action/github-action-benchmark@v1.14.0
        with:
          name: Benchmarks
          tool: benchmarkdotnet
          output-file-path: BenchmarkDotNet.Artifacts/results/LeetCode.Benchmarks.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
