name: Build and Benchmark

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      # TODO: Remove once fixed: https://github.com/dotnet/format/issues/1519
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format --version "6.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: Run dotnet format
        id: format
        # TODO: Rename to dotnet format once #1519 fixed
        run: dotnet-format --verbosity diagnostic --verify-no-changes

      - name: Run dotnet test
        id: test
        run: dotnet test --configuration Release
      
      - name: Run dotnet benchmark
        id: benchmark
        run: |
          cd ./Benchmarks
          dotnet run --configuration Release --memory --filter Leetcode.Benchmarks* --warmupCount 2 --minIterationCount 4 --maxIterationCount 8
