name: Build and Benchmark

on:
  push:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          include-prerelease: true
          dotnet-version: |
            6.0.x

      - name: Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: Run dotnet format
        id: format
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Run dotnet test
        id: test
        run: dotnet test --configuration Release

      - name: Run C# benchmark
        id: benchmark-csharp
        run: |
          dotnet run \
            --project ./Benchmarks.CSharp/Benchmarks.CSharp.csproj \
            --framework net6.0
            --configuration Release \
            --filter LeetCode.CSharpBenchmarks* \
            --exporters json \
            --memory \
            --job Short

      - name: Run F# benchmark
        id: benchmark-fsharp
        run: |
          dotnet run \
            --project ./Benchmarks.FSharp/Benchmarks.FSharp.fsproj \
            --framework net6.0
            --configuration Release \
            --filter LeetCode.FSharpBenchmarks* \
            --exporters json \
            --memory \
            --job Short

      - name: Store C# benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: C# Benchmarks
          tool: benchmarkdotnet
          output-file-path: BenchmarkDotNet.Artifacts/results/LeetCode.CSharpBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false

      - name: Store F# benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: F# Benchmarks
          tool: benchmarkdotnet
          output-file-path: BenchmarkDotNet.Artifacts/results/LeetCode.FSharpBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-fetch-gh-pages: true
          auto-push: true