name: Build and Benchmark

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      # TODO: Remove once fixed: https://github.com/dotnet/format/issues/1519
      - name: Install dotnet format
        run: |
          dotnet tool install -g dotnet-format --version "6.*" \
            --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: Run dotnet format
        id: format
        # TODO: Rename to dotnet format once #1519 fixed
        run: dotnet-format --verbosity diagnostic --verify-no-changes

      - name: Run dotnet test
        id: test
        run: dotnet test --configuration Release
      
      - name: Run C# benchmark
        id: benchmark-csharp
        run: | 
          dotnet run \
            --project ./Benchmarks.CSharp/Benchmarks.CSharp.csproj \
            --configuration Release \
            --filter LeetCode.CSharpBenchmarks* \
            --exporters json \
            --memory --warmupCount 3 --minIterationCount 6 --maxIterationCount 9

      - name: Run F# benchmark
        id: benchmark-fsharp
        run: | 
          dotnet run \
            --project ./Benchmarks.FSharp/Benchmarks.FSharp.csproj \
            --configuration Release \
            --filter LeetCode.FSharpBenchmarks* \
            --exporters json \
            --memory --warmupCount 3 --minIterationCount 6 --maxIterationCount 9
      
      - name: Store C# benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'benchmarkdotnet'
          output-file-path: Benchmarks.CSharp/BenchmarkDotNet.Artifacts/results/LeetCode.CSharpBenchmarks-report-full-compressed.json
      
      - name: Store F# benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'benchmarkdotnet'
          output-file-path: Benchmarks.FSharp/BenchmarkDotNet.Artifacts/results/LeetCode.FSharpBenchmarks-report-full-compressed.json
