name: Build and Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: Run dotnet format
        id: format
        run: dotnet format --verbosity diagnostic --verify-no-changes --no-restore

      - name: Run dotnet test
        id: test
        run: dotnet test --configuration Release --no-restore

  benchmark:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: List problems
        id: list-problems
        run: |
          dotnet run \
            --project ./LeetCode/LeetCode.csproj \
            list

      - name: Run benchmarks
        id: run-benchmarks
        run: |
          dotnet run \
            --project ./LeetCode/LeetCode.csproj \
            --configuration Release \
            workflow

      - name: Store benchmark results
        id: store-benchmarks
        if: ${{ github.event_name == 'push' }}
        uses: benchmark-action/github-action-benchmark@v1.19.2
        with:
          name: Benchmarks
          tool: benchmarkdotnet
          output-file-path: BenchmarkDotNet.Artifacts/results/LeetCode.Benchmarks.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
